server:
  port: 8001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/monitoring_db
    username: fleet_user
    password: fleet_pass
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect