apiVersion: 1

datasources:
  - name: MQTT
    type: grafana-mqtt-datasource
    access: proxy
    isDefault: false
    jsonData:
      uri: tcp://mosquitto:1883
      clientId: grafana-client
      topic: trains/#
      qos: 0