package com.actia.tracking_service.dto;

/**
 * Inbound payload for POST /trains (create) and PUT /trains/{id} (update).
 *
 * trainId is omitted — on create it is generated by the DB sequence train_id_seq;
 * on update the identity comes from the {id} path variable.
 */
public record TrainRequest(
        String name,
        String mission,
        String baseline,
        String diversity,
        String database
) {}
